version: '3.3'
services:
   db:
     container_name: dbcontainer
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - '3306:3306'
     expose:
       - '3306'
     environment:
       MYSQL_ROOT_PASSWORD: 12345
   app:
     container_name: appcontainer
     depends_on:
       - db
     links:
       - db
     build: .
     ports:
       - '8000:8000'
     environment:
       APP_DB_HOST: db:3306
volumes:
    db_data:
